/*
 * Create 2 film tables, the only difference being the order of the rows.
 *
 * Question: calculate the disk usage of each row when the text values are null.
 */
CREATE TABLE film (
    film_id SERIAL NOT NULL,
    release_date timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    description text,
    length INTEGER NOT NULL
);

CREATE TABLE film2 (
    release_date timestamp with time zone DEFAULT now() NOT NULL,
    film_id SERIAL NOT NULL,
    length INTEGER NOT NULL,
    description text,
    title text
);

INSERT INTO film (title, description, length) VALUES
    (NULL, NULL, 5),
    ('toy story', NULL, 89),
    ('cars', 'cars come to life and live like people', 122);

INSERT INTO film2 (title, description, length) VALUES
    (NULL, NULL, 5),
    ('toy story', NULL, 89),
    ('cars', 'cars come to life and live like people', 122);

/*
 * measure the disk usage of each row
 */
SELECT
    film_id,
    pg_column_size(film.*)
FROM film;

SELECT
    film_id,
    pg_column_size(film2.*)
FROM film2;

/*
 * A third way to store the same information.
 *
 * We've refactored the film table to move the description into a separate table.
 * This reduces the overhead needed to store each tuple in film3,
 * but greatly increases the overhead needed to store the full "joined" table.
 *
 * Question: calculate the disk usage of each row when the text values are null.
 */

CREATE TABLE film3 (
    release_date timestamp with time zone DEFAULT now() NOT NULL,
    film_id SERIAL NOT NULL,
    --film_id SERIAL UNIQUE NOT NULL,
    --film_id SERIAL PRIMARY,
    --film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length INTEGER NOT NULL,
    description text,
    title text
    -- PRIMARY KEY (film_id)
);

CREATE TABLE film_description (
    film_id INTEGER NOT NULL /*UNIQUE REFERENCES film3(film_id)*/,
    description text NOT NULL
);

INSERT INTO film3 (title, length) VALUES
    (NULL, 5),
    ('toy story', 89),
    ('cars', 122);

INSERT INTO film_description (film_id, description) VALUES
    (3, 'cars come to life and live like people');

CREATE VIEW film3_view AS (
SELECT
    film_id,
    title,
    release_date,
    length,
    description
FROM film
LEFT JOIN film_description USING (film_id)
);
